#!/usr/bin/env bash
# Configures Nginx to run as nginx user on port 8080
sed -i 's/^user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:80/listen [::]:8080/g' /etc/nginx/sites-enabled/default
nginx -s stop 2>/dev/null || true
nginx
